import test from 'node:test';import assert from 'node:assert/strict';import {createBridge} from '../server.mjs';import {beepsterRoute} from '../beepster-proxy.mjs';
test('G2 allowlist excludes deletion and legacy GET sending routes',()=>{assert.ok(beepsterRoute('POST','/beepster/v1/chats/archive'));assert.equal(beepsterRoute('GET','/beepster/v1/chats/archive'),false);for(const path of ['/beepster/v1/chats','/beepster/v1/chats/a/messages','/beepster/v1/chats/a/messages/b','/beepster/v1/attachments/'+'a'.repeat(24)+'/preview'])assert.ok(beepsterRoute('GET',path));for(const [method,path] of [['GET','/beepster/v1/chats/a/reply'],['POST','/beepster/v1/chats/a/delete-message'],['POST','/beepster/v1/agents/approvals/a/decision'],['GET','/beepster/../health']])assert.equal(beepsterRoute(method,path),false);});
test('G2 auth precedes messaging; gateway secret stays on Mac and JSON send is forwarded',async()=>{const requests=[];const server=createBridge({clientToken:'g2-secret',beepsterToken:'gateway-secret'},{fetcher:async(url,options)=>{requests.push({url,options});return new Response(JSON.stringify({state:'pending'}),{status:202});}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{assert.equal((await fetch(base+'/beepster/v1/chats')).status,401);assert.equal(requests.length,0);const response=await fetch(base+'/beepster/v1/chats/a/messages',{method:'POST',headers:{Authorization:'Bearer g2-secret','Content-Type':'application/json'},body:JSON.stringify({text:'synthetic',requestID:'test'})});assert.equal(response.status,202);assert.equal(requests[0].options.headers.Authorization,'Bearer gateway-secret');assert.equal(requests[0].url,'http://127.0.0.1:8794/v1/chats/a/messages');assert.equal(JSON.parse(requests[0].options.body).text,'synthetic');assert.ok(!(await response.text()).includes('secret'));assert.equal((await fetch(base+'/beepster/v1/chats/a/reply',{headers:{Authorization:'Bearer g2-secret'}})).status,404);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});
test('Pome-only bridge reports unavailable Beepster without leaking its home credential',async()=>{const server=createBridge({clientToken:'g2',homeToken:'home'});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const r=await fetch('http://127.0.0.1:'+server.address().port+'/beepster/v1/chats',{headers:{Authorization:'Bearer g2'}});assert.equal(r.status,503);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});

test('bundled emoji assets are served without pairing, with correct MIME and bytes',async(t)=>{
 const {mkdtemp,mkdir,writeFile,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const path=await import('node:path');const dir=await mkdtemp(path.join(tmpdir(),'g2-static-'));
 const emoji=path.join(dir,'beepster/dist/emoji');await mkdir(emoji,{recursive:true});const data=Buffer.from([0,127,255]);await writeFile(path.join(emoji,'g2-pixels.bin'),data);await writeFile(path.join(emoji,'catalog.json'),'{}');await writeFile(path.join(emoji,'atlas.png'),data);
 const s=createBridge({clientToken:'client',homeToken:'home'},{assets:path.join(dir,'pome/dist')});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(async()=>{s.closeAllConnections();await new Promise(r=>s.close(r));await rm(dir,{recursive:true,force:true});});const root='http://127.0.0.1:'+s.address().port;
 for(const [name,mime] of [['g2-pixels.bin','application/octet-stream'],['catalog.json','application/json'],['atlas.png','image/png']]){const r=await fetch(root+'/beepster/emoji/'+name);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),mime);if(name==='g2-pixels.bin')assert.deepEqual(Buffer.from(await r.arrayBuffer()),data);}
 assert.equal((await fetch(root+'/beepster/emoji/private.json')).status,401);
});

test('archive requires G2 authentication and forwards only the submitted chat IDs',async t=>{const calls=[];const server=createBridge({clientToken:'g2-test',beepsterToken:'gateway-test'},{fetcher:async(url,options)=>{calls.push({url,body:JSON.parse(options.body)});return Response.json({archived:true});}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});const url='http://127.0.0.1:'+server.address().port+'/beepster/v1/chats/archive',body=JSON.stringify({chatIDs:['synthetic-container']});assert.equal((await fetch(url,{method:'POST',body})).status,401);assert.equal(calls.length,0);assert.equal((await fetch(url,{method:'POST',headers:{Authorization:'Bearer g2-test'},body})).status,200);assert.deepEqual(calls,[{url:'http://127.0.0.1:8794/v1/chats/archive',body:{chatIDs:['synthetic-container']}}]);});
