// Read-only live acceptance. Evidence contains no message text, IDs, addresses or credentials.
import {execFileSync} from 'node:child_process';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
import {API} from '../src/api';import {defaults,messageAttachments} from '../src/model';import {mediaFrames} from '../src/media';
const token=execFileSync('/usr/bin/security',['find-generic-password','-s','org.organikapps.even','-a','client','-w'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();const api=new API({...defaults,url:'http://127.0.0.1:7858',token});
const start=Date.now(),inbox=await api.chats('primary'),chat=inbox.items.find(c=>c.name===process.argv[2]);assert.ok(chat?.merge);
assert.ok(inbox.items.every((c,i)=>!i||(inbox.items[i-1].lastActivity||0)>=(c.lastActivity||0)));
const listMilliseconds=Date.now()-start;const messages=await api.conversation(chat),results=[];
for(const m of messages.items){for(const a of messageAttachments(m)){const r=await fetch(api.settings.url+'/beepster/v1/attachments/'+a.id+'/preview?format=json&animate=1',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(25000)});const p=await r.json();const service=chat.merge.members.find(x=>x.id===m.sourceChatID)?.network||'';if(r.ok){const frames=mediaFrames(p);assert.ok(frames[0].length);results.push({service,kind:a.kind,status:r.status,width:p.width,height:p.height,frames:frames.length,g2BMP:true});}else results.push({service,kind:a.kind,status:r.status,code:p.code,stage:p.stage});}}
const evidence={connectorBuild:'68',beepsterG2Version:'0.1.4',listMilliseconds,targetPosition:inbox.items.indexOf(chat)+1,descendingActivity:true,results,sends:0,hardwareTested:false};console.log(JSON.stringify(evidence,null,2));if(process.argv[3])writeFileSync(process.argv[3],JSON.stringify(evidence,null,2)+'\n');
assert.ok(results.some(r=>r.service==='iMessage'&&r.kind==='image'&&r.status===200));assert.ok(results.some(r=>r.service==='Instagram'&&r.status===200));assert.ok(results.every(r=>r.status===200||r.code==='MEDIA_MISSING'));
