import test from 'node:test';import assert from 'node:assert/strict';
import {API} from '../src/api';import {Beepster} from '../src/controller';import {loadSettings} from '../src/model';import {Display,menuActions} from '../src/display';
const chats=[{id:'one',name:'First',network:'iMessage',unreadCount:0,preview:'',timestamp:''},{id:'two',name:'Second',network:'WhatsApp',unreadCount:1,preview:'',timestamp:''}];
function fixture(){const api=new API(loadSettings('{"refresh":0}'),true);api.chats=async()=>({items:structuredClone(chats)});const display={show:()=>{},record:async()=>{},exit:async()=>{},idle:async()=>{}} as unknown as Display;const app=new Beepster(api,display);let saved:any;app.saveSettings=async s=>{saved=structuredClone(s);};return {api,display,app,saved:()=>saved};}
test('custom system actions match requested order with no duplicated firmware controls',()=>{assert.deepEqual(menuActions.map(a=>a.label),['Quick reply','Dictate','Pin / unpin','Archive','Refresh']);});
test('all system actions defer until close and keep the menu-opening target',()=>{for(const action of menuActions){const display=new Display({} as HTMLElement,false),calls:unknown[]=[];(display as any).sentFavorite={key:'one',pinned:false};display.onMenuAction=(a,t)=>calls.push([a,t?.key]);(display as any).event({sysEvent:{eventType:4}});(display as any).sentFavorite={key:'two',pinned:false};(display as any).event({menuItemClickEvent:{itemID:action.id}});assert.equal(calls.length,0);(display as any).event({sysEvent:{eventType:5}});assert.deepEqual(calls,[[action.action,'one']]);}});
test('pin persists, stays first across refresh, unpins, and ignores obsolete shortcut remapping',async t=>{const f=fixture();t.after(()=>f.app.dispose());await f.app.start();await f.app.systemAction('pin',{key:'two',pinned:false});assert.deepEqual(f.saved().pinnedChats,[{id:'two',name:'Second'}]);assert.equal(f.app.page?.rows[0].key,'two');await f.app.poll();assert.equal(f.app.page?.rows[0].key,'two');await f.app.systemAction('pin',{key:'two',pinned:true});assert.deepEqual(f.saved().pinnedChats,[]);assert.equal(f.app.page?.rows[0].key,'one');f.api.settings.threadFavorite='none';await f.app.systemAction('replies');assert.equal(f.app.page?.kind,'replies');});
test('failed pin persistence retains order and state',async t=>{const f=fixture();t.after(()=>f.app.dispose());await f.app.start();f.app.saveSettings=async()=>{throw Error('Storage unavailable');};await f.app.systemAction('pin',{key:'two',pinned:false});assert.deepEqual(f.api.settings.pinnedChats,[]);assert.equal(f.app.page?.rows[0].key,'one');assert.match(f.app.notice,/Storage unavailable/);});
test('configured pinned order resolves chats beyond first page without inventing missing chats',async()=>{const api=new API(loadSettings('{"pinnedChats":[{"id":"two","name":"Second"},{"id":"missing","name":"Gone"},{"id":"one","name":"First"}]}'));let calls=0;api.chats=async(_,cursor)=>{calls++;return cursor?{items:[chats[1]],hasMore:false}:{items:[chats[0]],hasMore:true,nextCursor:'page2'};};const result=await api.inbox();assert.equal(calls,2);assert.deepEqual(result.items.map(c=>c.id),['one','two']);assert.equal(result.nextCursor,'page2');const f=fixture();f.api.settings=api.settings;f.api.chats=api.chats;try{await f.app.start();assert.deepEqual(f.app.page?.rows.map(r=>r.key),['two','one','more']);}finally{f.app.dispose();}});
test('archive targets the selected container, removes it only after success, and clears its pin',async t=>{const f=fixture();t.after(()=>f.app.dispose());await f.app.start();await f.app.systemAction('pin',{key:'two',pinned:false});const calls:any[]=[];f.api.request=async(path,method,body)=>{calls.push({path,method,body});return {archived:true} as any;};await f.app.systemAction('archive',{key:'two',pinned:true});assert.deepEqual(calls,[{path:'/beepster/v1/chats/archive',method:'POST',body:{chatIDs:['two']}}]);assert.equal(f.app.page?.kind,'inbox');assert.ok(!f.app.page?.rows.some(r=>r.key==='two'));assert.deepEqual(f.saved().pinnedChats,[]);});
test('failed archive leaves chat, pin and current page intact',async t=>{const f=fixture();t.after(()=>f.app.dispose());await f.app.start();await f.app.systemAction('pin',{key:'two',pinned:false});f.api.archive=async()=>{throw Error('Archive unavailable');};await f.app.systemAction('archive',{key:'two',pinned:true});assert.ok(f.app.page?.rows.some(r=>r.key==='two'));assert.equal(f.api.settings.pinnedChats[0].id,'two');assert.match(f.app.notice,/Archive unavailable/);});
test('inbox, threads and message options contain no reply, dictation or refresh rows',async t=>{const f=fixture();t.after(()=>f.app.dispose());await f.app.start();assert.ok(!f.app.page?.rows.some(r=>r.key==='refresh'));await f.app.openChat(chats[0]);assert.ok(!f.app.page?.rows.some(r=>['refresh','dictate','replies'].includes(r.key||'')));assert.equal(f.app.page?.index,0);await f.app.openMessage(chats[0],{id:'text',sender:'First',text:'hello',time:''});await f.app.input(0);assert.deepEqual(f.app.page?.rows.map(r=>r.label),['Back to message']);});
test('poll pauses while the system menu is open; refresh updates a message reader',async t=>{const f=fixture();t.after(()=>f.app.dispose());await f.app.start();let count=0;f.api.chats=async()=>{count++;return {items:chats};};Object.defineProperty(f.display,'menuOpen',{value:true,configurable:true});await f.app.poll();assert.equal(count,0);Object.defineProperty(f.display,'menuOpen',{value:false});await f.app.openChat(chats[0]);const m={id:'text',sender:'First',text:'before',time:''};await f.app.openMessage(chats[0],m);f.api.conversation=async()=>({items:[{...m,text:'after'}]});await f.app.systemAction('refresh');assert.equal(f.app.page?.kind,'message');assert.ok(f.app.page?.lines?.some(l=>l.endsWith('after')));});
