import test from 'node:test';import assert from 'node:assert/strict';
import {API} from '../src/api';import {Beepster} from '../src/controller';import {loadSettings,type Message} from '../src/model';import {bottomOffset,threadBottom,threadWindow,threadStep} from '../src/thread-content';
const chat={id:'demo',name:'Alex',network:'iMessage',unreadCount:0,preview:'',timestamp:''};
const message=(id:string,text:string):Message=>({id,sender:'Alex',time:id+':00',text,timestamp:`2026-09-11T${id.padStart(2,'0')}:00:00Z`});
function fixture(){const api=new API(loadSettings('{"refresh":0}'),true),screens:any[]=[],display={show:(s:any)=>screens.push(s),record:async()=>{},exit:async()=>{}} as any;const app=new Beepster(api,display);return {app,api,screens};}
test('thread contains full oldest-first messages and opens at newest bottom',async t=>{const f=fixture();t.after(()=>f.app.dispose());const long='Every word remains readable. '.repeat(25);f.api.messages=async()=>({items:[message('3','newest'),message('1','oldest'),message('2',long)]});await f.app.start();await f.app.openChat(chat);const p=f.app.page!;assert.equal(p.kind,'chat');assert.ok(p.lines!.findIndex(l=>l.endsWith('oldest'))<p.lines!.findIndex(l=>l.endsWith('newest')));assert.equal(p.lines!.filter(l=>l.includes('Every')).join(' ').split('Every').length-1,25);assert.equal(p.offset,threadBottom(p));assert.ok(f.screens.at(-1).lines.some((l:string)=>l.endsWith('newest')));await f.app.input(0);assert.equal(f.app.page,p);});
test('long-message single-line scrolling overlaps the viewport, reaches both ends, and requires no message-open tap',async t=>{const f=fixture();t.after(()=>f.app.dispose());f.api.messages=async()=>({items:[message('1','Long readable text '.repeat(80))]});await f.app.start();await f.app.openChat(chat);const p=f.app.page!,end=p.offset!,before=f.screens.at(-1).lines;await f.app.input(1);assert.equal(p.offset,end-1);assert.deepEqual(f.screens.at(-1).lines.slice(1),before.slice(0,5));await f.app.input(2);assert.equal(p.offset,end);for(let i=0;i<100;i++)await f.app.input(1);assert.equal(p.offset,0);await f.app.input(1);assert.equal(p.offset,0);assert.equal(f.app.page?.kind,'chat');});
test('new messages follow the bottom but preserve the line anchor when reading history',async t=>{const f=fixture();t.after(()=>f.app.dispose());let items=[message('1','Old text '.repeat(50)),message('2','latest')];f.api.messages=async()=>({items});await f.app.start();await f.app.openChat(chat);items=[...items,message('3','just arrived')];await f.app.poll();assert.equal(f.app.page?.offset,threadBottom(f.app.page!));assert.ok(f.screens.at(-1).lines.some((l:string)=>l.endsWith('just arrived')));await f.app.input(1);await f.app.input(1);const p=f.app.page!,key=p.lineKeys![p.offset!];items=[...items,message('4','new arrival')];await f.app.poll();assert.equal(p.lineKeys![p.offset!],key);assert.ok(p.offset!<bottomOffset(p.lines!));});
test('scrolling above loaded history prepends older messages without jumping to the oldest page',async t=>{const f=fixture();t.after(()=>f.app.dispose());f.api.messages=async(_,cursor)=>cursor?{items:[message('1','older history '.repeat(30))],hasMore:false}:{items:[message('2','current text '.repeat(30))],hasMore:true,nextCursor:'older-page'};await f.app.start();await f.app.openChat(chat);const old=f.app.page!;old.offset=0;const key=old.lineKeys![1];await f.app.input(1);const p=f.app.page!;assert.equal(p.messages?.length,2);assert.equal(p.cursor,null);assert.equal(p.lineKeys![threadWindow(p,p.offset!).end],key);assert.ok(p.offset!>0);});
test('attachment opens from its visible thread and back restores exact scroll position',async t=>{const f=fixture();t.after(()=>f.app.dispose());f.api.messages=async()=>({items:[{...message('1','Caption'),attachment:{id:'a'.repeat(24),kind:'image'}}]});await f.app.start();await f.app.openChat(chat);const p=f.app.page!,offset=p.offset;assert.ok(p.lines!.some(l=>l.endsWith('Caption')));assert.ok(p.lines!.includes('Tap: Photo'));await f.app.input(0);assert.equal(f.app.page?.kind,'media');f.app.back();assert.equal(f.app.page,p);assert.equal(p.offset,offset);});
test('reactions update within the full thread while images-off suppresses attachment controls',async t=>{const f=fixture();t.after(()=>f.app.dispose());f.api.settings.images=false;const m={...message('1','Full text'),attachment:{id:'a'.repeat(24),kind:'image'}};f.api.messages=async()=>({items:[m]});await f.app.start();await f.app.openChat(chat);assert.ok(!f.app.page!.lines!.some(l=>l.startsWith('Tap:')));await f.app.input(0);assert.equal(f.app.page?.kind,'chat');f.api.messages=async()=>({items:[{...m,reactions:[{sender:'Alex',text:'👍'}]}]});await f.app.poll();assert.ok(f.app.page!.lines!.some(l=>l.includes('Thumbs up')));assert.ok(f.app.page!.lines!.some(l=>l.endsWith('Full text')));});

test('message boundaries use divider metadata without consuming a blank text row',async t=>{const f=fixture();t.after(()=>f.app.dispose());f.api.settings.showTime=false;f.api.messages=async()=>({items:[message('1','First'),message('2','Second')]});await f.app.start();await f.app.openChat(chat);const p=f.app.page!;assert.deepEqual(p.lines,['Alex · First','Alex · Second']);assert.deepEqual(p.lineDividers,[false,true]);assert.deepEqual(f.screens.at(-1).dividers,[false,true]);});

test('sender, time and text share wrapped lines with middots and honor visibility settings',async()=>{const {threadContent}=await import('../src/thread-content');const m={...message('1','break time!'),sender:'Jane Lynch',time:'1:34pm'};for(const [showSender,showTime,expected] of [[true,true,'Jane Lynch · 1:34pm · break time!'],[true,false,'Jane Lynch · break time!'],[false,true,'1:34pm · break time!'],[false,false,'break time!']] as const){const content=threadContent(chat,[m],{...loadSettings('{}'),showSender,showTime});assert.deepEqual(content.lines,[expected]);assert.deepEqual(content.lineIcons,['apple_messages']);}const long=threadContent(chat,[{...m,text:'long text '.repeat(40)}],loadSettings('{}'));assert.ok(long.lines.length>1);assert.ok(long.lines[0].startsWith('Jane Lynch · 1:34pm · long'));assert.equal(long.lines.slice(1).filter(l=>l.includes('Jane')).length,0);});

function layout(...lengths:number[]){const lines:string[]=[],lineMessages:Message[]=[];lengths.forEach((n,i)=>{const m=message(String(i+1),'fixture');for(let row=0;row<n;row++){lines.push(`${i}:${row}`);lineMessages.push(m);}});return {lines,lineMessages};}
test('short messages are kept whole and swipes advance to message boundaries',()=>{const p=layout(4,3,2);assert.deepEqual(threadWindow(p,0),{start:0,end:4});assert.equal(threadStep(p,0,1),4);assert.deepEqual(threadWindow(p,4),{start:4,end:9});assert.equal(threadStep(p,4,1),7);assert.equal(threadStep(p,7,-1),4);assert.equal(threadStep(p,4,-1),0);assert.equal(threadBottom(p),4);});
test('long messages scroll internally before advancing and reverse from their final viewport',()=>{const p=layout(2,9,2);assert.deepEqual(threadWindow(p,0),{start:0,end:2});let offset=threadStep(p,0,1);assert.equal(offset,2);for(const expected of [3,4,5]){offset=threadStep(p,offset,1);assert.equal(offset,expected);assert.deepEqual(threadWindow(p,offset),{start:offset,end:offset+6});}assert.equal(threadStep(p,offset,1),11);assert.equal(threadStep(p,11,-1),5);assert.equal(threadStep(p,2,-1),0);});
test('a deferred attachment is neither rendered nor marked read until its message is shown',async t=>{const f=fixture();t.after(()=>f.app.dispose());f.api.settings.markRead=false;f.api.messages=async()=>({items:[message('1','first'),{...message('2','second'),attachment:{id:'a'.repeat(24),kind:'image'}}]});await f.app.start();await f.app.openChat(chat);const p=f.app.page!,first=p.messages!.find(m=>m.id==='1')!,second=p.messages!.find(m=>m.id==='2')!;p.lines=['a','b','c','d','e','photo','Tap: Photo'];p.lineMessages=[first,first,first,first,first,second,second];p.offset=0;const reads:string[]=[];f.api.request=async(_path:any,_method:any,body:any)=>{reads.push(body.messageID);return {} as any;};f.api.settings.markRead=true;await f.app.input(1);assert.deepEqual(f.screens.at(-1).lines,['a','b','c','d','e']);assert.deepEqual(reads,['1']);await f.app.input(0);assert.equal(f.app.page,p);await f.app.input(2);assert.deepEqual(f.screens.at(-1).lines,['photo','Tap: Photo']);assert.deepEqual(reads,['1','2']);});
