import {prepareEmoji} from './emoji';
import './style.css';
import {Display,menuActions} from './display';import {API} from './api';import {Beepster} from './controller';import {loadSettings} from './model';import {SettingsStore} from './storage';import {settingsUI} from './settings';
const demo=new URLSearchParams(location.search).get('demo')==='1';
const root=document.querySelector<HTMLElement>('#app')!,settings=document.createElement('div'),side=document.createElement('aside');side.className='preview-panel';const heading=document.createElement('h2');heading.textContent=demo?'Interactive G2 demo':'Glasses preview';const preview=document.createElement('div');preview.className='glasses';side.append(heading,preview);root.append(settings,side);
const display=new Display(preview,demo),api=new API(loadSettings(demo?(localStorage.getItem('beepster.demo.settings')||'{}'):'{}'),demo),app=new Beepster(api,display);
for(const [name,type] of [['↑',1],['Select',0],['↓',2],['Back',3]] as const){const b=document.createElement('button');b.textContent=name;b.onclick=()=>void(app.input(type));side.append(b);}
const menuButton=document.createElement('button');menuButton.textContent='System menu';side.append(menuButton);menuButton.onclick=()=>{const menu=document.createElement('div');menu.className='preview-system-menu';const selected=app.page?.kind==='inbox'?app.page.chats?.find(c=>c.id===app.page!.rows[app.page!.index]?.key):app.chat;for(const action of menuActions){const b=document.createElement('button');b.textContent=action.label;b.onclick=()=>{menu.remove();void app.systemAction(action.action,selected?{key:selected.id,pinned:false}:null);};menu.append(b);}const close=document.createElement('button');close.textContent='Dismiss menu';close.onclick=()=>menu.remove();menu.append(close);side.querySelector('.preview-system-menu')?.remove();side.append(menu);};
const status=document.createElement('p');status.setAttribute('role','status');display.onDisplayStatus=t=>{status.textContent=t;};display.onMicrophoneStatus=t=>{status.textContent=t;};side.append(status);
const retry=document.createElement('button');retry.textContent='Retry glasses display';retry.onclick=()=>display.retry();side.append(retry);
if(demo){const note=document.createElement('p');note.textContent='Synthetic conversations only. Demo replies never reach Beeper.';side.append(note);}
let store:SettingsStore|undefined;app.saveSettings=async s=>{if(demo)localStorage.setItem('beepster.demo.settings',JSON.stringify(s));else {if(!store)throw Error('Settings are still loading');await store.save(s);}};
settings.textContent='Loading saved Beepster settings…';
void(async()=>{if(!demo){await display.connect();store=new SettingsStore(display.bridge!,localStorage);Object.assign(api.settings,await store.load());}await prepareEmoji();settingsUI(settings,app);let lastSettings=JSON.stringify(api.settings);app.onChange=()=>{status.textContent=app.notice;const current=JSON.stringify(api.settings);if(current!==lastSettings){lastSettings=current;settingsUI(settings,app);}};await app.start();})().catch((error)=>{settings.textContent=error instanceof Error&&error.message.startsWith('Emoji')?error.message:'Could not load saved settings. Reopen Beepster in Even. Your settings have not been replaced.';});
document.addEventListener('keydown',e=>{if((e.target as HTMLElement).closest('input,textarea,select,button'))return;const types:Record<string,number>={ArrowUp:1,ArrowDown:2,Enter:0,Escape:3};if(e.key in types){e.preventDefault();void app.input(types[e.key]);}});
if(demo)document.addEventListener('visibilitychange',()=>void app.input(document.hidden?6:5));window.addEventListener('pagehide',()=>app.dispose());
