import {Beepster} from './controller';
import {API} from './api';
import {loadSettings,pairing,emojiDefaults,shortcutOptions,type Settings} from './model';
import {serviceOptions} from './services';
type Emoji={id:number;key:string;emoji:string;label:string;group:string};
let catalog:Emoji[]=[];
const replyChoices=['Yes','No','On my way','Thanks! 👍','Thanks!','Sounds good','Got it','Okay','Be there soon','Running late','Call you later','Can’t talk right now','I’ll get back to you','Love you','See you soon','Good morning','Good night'];
export function settingsUI(root:HTMLElement,app:Beepster){
 root.replaceChildren();let draft=loadSettings(JSON.stringify(app.api.settings)),tab=(root.dataset.settingsTab==='Shortcuts'?'Pinned chats':root.dataset.settingsTab)||'Setup';
 const el=<K extends keyof HTMLElementTagNameMap>(tag:K,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e;};
 const header=el('header');header.append(el('h1','Beepster'),el('p','Settings for your G2 glasses.'));
 const nav=el('nav','','organik-tabs');nav.setAttribute('aria-label','Settings');nav.setAttribute('role','tablist');const panel=el('section','','organik-panel'),status=el('p','','status');status.setAttribute('role','status');const save=el('button','Save & apply','organik-apply');save.type='button';root.append(header,nav,panel,status,save);
 const note=(text:string,host:HTMLElement=panel)=>host.append(el('p',text,'hint'));
 const heading=(text:string)=>panel.append(el('h2',text));
 const button=(text:string,action:()=>void|Promise<void>,host:HTMLElement=panel)=>{const b=el('button',text,'secondary');b.type='button';b.onclick=()=>void action();host.append(b);return b;};
 const checkbox=(text:string,checked:boolean,change:(v:boolean)=>void,host:HTMLElement=panel)=>{const label=el('label','','choice'),input=el('input');input.type='checkbox';input.checked=checked;input.onchange=()=>change(input.checked);label.append(input,document.createTextNode(text));host.append(label);return input;};
 const check=(text:string,key:'hideLinks'|'showSender'|'showTime'|'markRead'|'images'|'gifFrames')=>checkbox(text,draft[key],v=>draft[key]=v);
 const select=(text:string,value:string,options:[string,string][],change:(v:string)=>void,host:HTMLElement=panel)=>{const label=el('label',text),input=el('select');for(const [v,t] of options){const o=el('option',t);o.value=v;input.append(o);}input.value=value;input.onchange=()=>change(input.value);label.append(input);host.append(label);return input;};
 const setting=(text:string,key:'refresh'|'lineWidth'|'contrast'|'longPress'|'threadShortcut'|'threadFavorite'|'chatFavorite'|'language',options:[string,string][])=>select(text,String(draft[key]),options,v=>(draft as unknown as Record<string,unknown>)[key]=typeof draft[key]==='number'?Number(v):v);
 function reorder(key:'quickReplies'|'emojiReplies',slot:number,delta:number){const next=slot+delta;[draft[key][slot],draft[key][next]]=[draft[key][next],draft[key][slot]];show();}
 function moveButtons(host:HTMLElement,key:'quickReplies'|'emojiReplies',slot:number){const up=button('↑',()=>reorder(key,slot,-1),host),down=button('↓',()=>reorder(key,slot,1),host);up.setAttribute('aria-label','Move '+(key==='emojiReplies'?'emoji':'reply')+' '+(slot+1)+' up');down.setAttribute('aria-label','Move '+(key==='emojiReplies'?'emoji':'reply')+' '+(slot+1)+' down');up.disabled=slot===0;down.disabled=slot===draft[key].length-1;}
 function thumb(value:string){const entry=catalog.find(e=>e.emoji===value);const icon=el('span',entry?'':value,'emoji-thumb');icon.setAttribute('aria-hidden','true');if(entry){icon.style.backgroundImage='url(./emoji/atlas.png?v=17-1)';icon.style.backgroundPosition=`-${entry.id%64*24}px -${Math.floor(entry.id/64)*24}px`;}return icon;}
 async function chooseEmoji(slot:number,trigger:HTMLButtonElement){
  if(!catalog.length){status.textContent='Loading emoji…';try{const r=await fetch('./emoji/catalog.json');if(!r.ok)throw Error();catalog=(await r.json()).entries;}catch{status.textContent='Could not load emoji. Reopen settings and try again.';return;}}
  status.textContent='';const overlay=el('div','','organik-overlay'),dialog=el('div','','organik-dialog');dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label','Choose emoji '+(slot+1));overlay.append(dialog);root.append(overlay);dialog.append(el('h2','Choose emoji '+(slot+1)));
  const close=()=>{overlay.remove();trigger.focus();};const closeButton=button('Close',close,dialog);let group='',page=0;const grid=el('div','','emoji-grid'),pages=el('div','','emoji-pages');
  select('Category','',[['','All categories'],...[...new Set(catalog.map(e=>e.group))].map(g=>[g,g] as [string,string])],v=>{group=v;page=0;render();},dialog);dialog.append(grid,pages);
  function render(){grid.replaceChildren();pages.replaceChildren();const matches=catalog.filter(e=>!group||e.group===group),count=Math.ceil(matches.length/60);for(const e of matches.slice(page*60,(page+1)*60)){const b=button('',()=>{draft.emojiReplies[slot]=e.emoji;overlay.remove();show();root.querySelector<HTMLButtonElement>(`[data-emoji-slot="${slot}"]`)?.focus();},grid);b.append(thumb(e.emoji));b.setAttribute('aria-label',e.label);b.title=e.label;}const prev=button('Previous',()=>{page--;render();},pages);prev.disabled=page===0;pages.append(el('span',`${page+1} / ${count}`));const next=button('Next',()=>{page++;render();},pages);next.disabled=page>=count-1;}
  overlay.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const targets=[...dialog.querySelectorAll<HTMLElement>('button:not(:disabled),select')],first=targets[0],last=targets.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};render();closeButton.focus();
 }
 function show(){root.dataset.settingsTab=tab;panel.replaceChildren();for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-selected',String(b.textContent===tab));
  if(tab==='Setup'){
   const connection=el('details');connection.open=!draft.token&&!app.api.demo;connection.append(el('summary',draft.token||app.api.demo?'Mac connection':'Connect to your Mac'));panel.append(connection);note('In Connector → Even G2, choose Copy pairing. Then paste it with the button below.',connection);
   button('Paste pairing from clipboard',async()=>{try{Object.assign(draft,pairing(await navigator.clipboard.readText()));show();status.textContent='Connection ready. Tap Save & apply.';}catch{status.textContent='Copy G2 pairing in Connector, then allow clipboard access and try again.';}},connection);
   button('Check connection',async()=>{try{const h=await new API(draft,app.api.demo).request<{beepster:boolean;dictation:boolean}>('/health');status.textContent=(h.beepster?'Beeper connected':'Beeper unavailable')+' · '+(h.dictation?'Voice replies ready':'Set up voice replies in Connector');}catch{status.textContent='Couldn’t reach Connector. Check Tailscale on your Mac and phone.';}},connection);
   heading('Included services');note('Choose which services appear in Beepster.');const services=el('div','','services');panel.append(services);for(const [id,label] of serviceOptions){const input=checkbox(label,!draft.services.length||draft.services.includes(id),v=>{const current=draft.services.length?draft.services:serviceOptions.map(([id])=>id);const next=v?[...new Set([...current,id])]:current.filter(x=>x!==id);if(!next.length){input.checked=true;status.textContent='Choose at least one service.';return;}draft.services=next;},services);}
   setting('Live refresh while open','refresh',[['5','5 seconds'],['15','15 seconds — recommended'],['30','30 seconds'],['60','1 minute'],['0','Manual only']]);note('Updates the inbox and open chats, including reactions. Pauses during dictation, reply review, sending, and when Beepster is closed.');
   check('Hide links in messages','hideLinks');setting('Photo appearance','contrast',[['natural','Natural'],['high-contrast','High contrast'],['original','Original']]);note('Natural balances detail. High contrast emphasizes light and dark. Original skips the extra adjustment. Photos are adapted to the green G2 display.');
   heading('Reading on G2');check('Show sender names','showSender');check('Show timestamps','showTime');check('Send read receipts for visible messages','markRead');check('Enable photo and thumbnail previews','images');check('Show GIF animation frames','gifFrames');setting('Text width','lineWidth',[['520','Full width'],['420','Shorter lines']]);note('Conversations open at the newest message. Swipe between messages; long messages scroll one line at a time. Tap to view visible attachments. Swipe through GIF frames. Double tap returns to the conversation.');
   heading('Voice replies');setting('Transcription language','language',[['en','English'],['es','Spanish'],['fr','French'],['de','German'],['it','Italian'],['ja','Japanese']]);note('Uses Parakeet on your Mac. Review every reply before sending.');
  }
  if(tab==='Pinned chats'){
   heading('Pinned chat order');note('Pin a conversation from the glasses system menu. Pinned chats stay above the rest of your inbox in this order. Drag a handle to reorder, or use the arrow buttons. Tap Save & apply when finished.');
   if(!draft.pinnedChats.length)note('No pinned chats yet. Select a conversation on G2 and choose Pin / unpin in the system menu.');
   const list=el('div','','pinned-chats');panel.append(list);
   draft.pinnedChats.forEach((chat,index)=>{const row=el('div','','pinned-chat');row.dataset.pinIndex=String(index);list.append(row);const handle=button('⠿',()=>{},row);handle.classList.add('drag-handle');handle.setAttribute('aria-label','Drag '+chat.name);row.append(el('span',chat.name,'pinned-name'));
    const move=(to:number)=>{if(to<0||to>=draft.pinnedChats.length||to===index)return;const [item]=draft.pinnedChats.splice(index,1);draft.pinnedChats.splice(to,0,item);show();};
    const up=button('↑',()=>move(index-1),row),down=button('↓',()=>move(index+1),row);up.disabled=index===0;down.disabled=index===draft.pinnedChats.length-1;up.setAttribute('aria-label','Move '+chat.name+' up');down.setAttribute('aria-label','Move '+chat.name+' down');const remove=button('Unpin',()=>{draft.pinnedChats.splice(index,1);show();},row);remove.setAttribute('aria-label','Unpin '+chat.name);
    let destination=index,dragging=false;handle.onpointerdown=e=>{dragging=true;destination=index;handle.setPointerCapture(e.pointerId);row.classList.add('dragging');};handle.onpointermove=e=>{if(!dragging)return;const rows=[...list.children] as HTMLElement[];destination=rows.reduce((best,item,i)=>Math.abs(e.clientY-(item.getBoundingClientRect().top+item.getBoundingClientRect().height/2))<Math.abs(e.clientY-(rows[best].getBoundingClientRect().top+rows[best].getBoundingClientRect().height/2))?i:best,0);rows.forEach((r,i)=>r.classList.toggle('drop-target',i===destination));};handle.onpointerup=()=>{dragging=false;row.classList.remove('dragging');for(const r of list.children)r.classList.remove('drop-target');move(destination);};handle.onpointercancel=()=>{dragging=false;for(const r of list.children)r.classList.remove('dragging','drop-target');};
   });
   heading('Glasses system menu');note('Quick reply → Dictate → Pin / unpin → Archive → Refresh. These actions use the selected conversation. Display off, Brightness, and Close are placed by Even’s firmware.');note('An asterisk marks pinned conversations on the green display. Archiving removes a conversation from the inbox; you can restore it in Beeper.');
  }
  if(tab==='Replies'){
   heading('Quick replies');note('Choose and order up to eight replies. Set unused slots to None. Your existing custom replies are available in the choices.');
   const options=[['','None'],...[...new Set([...draft.quickReplies,...replyChoices])].filter(Boolean).map(v=>[v,v])] as [string,string][];
   for(let i=0;i<8;i++){const row=el('div','','reply-slot');panel.append(row);select('Quick reply '+(i+1),draft.quickReplies[i]||'',options,v=>{while(draft.quickReplies.length<=i)draft.quickReplies.push('');draft.quickReplies[i]=v;},row);if(i<draft.quickReplies.length)moveButtons(row,'quickReplies',i);}
   heading('Emoji replies');note('Choose and order 15 emoji, using the same catalog as Pebble. Each sends the real emoji after you confirm.');
   while(draft.emojiReplies.length<15)draft.emojiReplies.push(emojiDefaults[draft.emojiReplies.length]);
   for(let i=0;i<15;i++){const row=el('div','','emoji-slot');panel.append(row);row.append(thumb(draft.emojiReplies[i]));const entry=catalog.find(e=>e.emoji===draft.emojiReplies[i]),b=button((i+1)+'. '+(entry?.label||draft.emojiReplies[i]),()=>chooseEmoji(i,b),row);b.classList.add('emoji-choice');b.dataset.emojiSlot=String(i);moveButtons(row,'emojiReplies',i);}
   note('Incoming reactions such as thumbs up appear on the original message. Quick replies are sent as new messages.');
  }
 }
 for(const name of ['Setup','Pinned chats','Replies']){const b=el('button',name);b.type='button';b.setAttribute('role','tab');b.onclick=()=>{tab=name;show();};nav.append(b);}show();
 if(!catalog.length)void fetch('./emoji/catalog.json').then(r=>r.json()).then(data=>{catalog=data.entries;if(root.isConnected&&tab==='Replies')show();}).catch(()=>{});
 save.onclick=async()=>{save.disabled=true;try{draft=loadSettings(JSON.stringify(draft));await app.applySettings(draft);const current=root.querySelector('.status');if(current)current.textContent='Saved. Settings applied to Beepster.';}catch(e){status.textContent=(e as Error).message;}finally{save.disabled=false;}};
}
